#!/usr/bin/env python3
#encoding:utf8

import sys, os
os.chdir(os.path.dirname(os.path.realpath(__file__)))
sys.path.insert(0, os.path.realpath("./lib"))

import click

from main import Main

@click.command()
@click.argument('command', nargs=1)
def handler(command):
    main = Main()
    if command == 'start':
        main.start()
    elif command == 'stop':
        main.stop()
    elif command == 'restart':
        main.restart()
    elif command == 'foreground':
        main.run()
    else:
        print("unknow command {0}".format(command))

if __name__ == "__main__":
    handler()

