#!/usr/bin/env python2
#encoding:utf8

import sys, os
path = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.realpath(path + "/lib"))
sys.path.insert(0, os.path.realpath(path))

import click

from main import Main

@click.command()
@click.argument('command', nargs=1)
@click.option('--conf', '-c', default='/etc/rpi-ui.conf', help='Configure File')
def handler(command, conf):
    main = Main(conf)
    if command == 'start':
        main.start()
    elif command == 'stop':
        main.stop()
    elif command == 'restart':
        main.restart()
    elif command == 'foreground':
        main.run()
    else:
        print("unknow command {0}".format(command))

if __name__ == "__main__":
    handler()

